version: "3"
services:

  django:
    image: python:3.6
    volumes:
      - .:/src
      - venv:/src/venv
    command: ["/src/tools/dev-django.sh", "0.0.0.0:8000"]
    environment:
      ADMIN_USERNAME: "admin"
      ADMIN_PASSWORD: "password"
      ADMIN_EMAIL: "admin@example.com"
      DATABASE_URL: "postgres://piaf:piaf@postgres:5432/piaf?sslmode=disable"
      ALLOW_SIGNUP: "True"
    ports:
      - 8000:8000

  webpack:
    image: node:8
    volumes:
      - .:/src
      - node_modules:/src/app/server/static/node_modules
    command: ["/src/tools/dev-webpack.sh"]
    environment:
      WEBPACK_HOST: "0.0.0.0"
      WEBPACK_PORT: "8080"
      WEBPACK_POLL_MILLIS: "1000"
    ports:
      - 8080:8080

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: "piaf"
      POSTGRES_PASSWORD: "piaf"
      POSTGRES_DB: "piaf"
      PGDATA: /var/lib/postgres/data
    ports:
      - 5432:5432
    volumes:
      - ./app/db:/var/lib/postgres/data

volumes:
  node_modules:
  venv:
