# Project information
site_name: 'piaf'
site_description: 'Outil d'annotation pour la question - réponse en français'
site_author: 'Guillaume Lancrenon'
site_url: 'https://etalab.github.io/piaf/'

# Repository
repo_name: 'etalab/piaf'
repo_url: 'https://github.com/etalab/piaf'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 Hiroki Nakayama'

theme:
  name: 'material'
  palette:
    primary: 'cyan'
    accent: 'cyan'
  show_sidebar: true

# Page tree
nav:
  - piaf: index.md
  - Getting started: getting-started.md
  - Tutorial: tutorial.md
  - Advanced:
    - AWS HTTPS settings: advanced/aws_https_settings.md
    - OAuth2 settings: advanced/oauth2_settings.md
  #- Release notes: release-notes.md
  #- Author's notes: authors-notes.md
  - FAQ: faq.md
  - Contributing: CONTRIBUTING.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Roadmap: roadmap.md
  - License: LICENSE.md
